version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "8002:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2513
      POSTGRES_DB: AvitoAnalytics
  parser:
    image: parser:latest
    ports:
      - "8001:8000"