spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:8001/AvitoAnalytics
    username: postgres
    password: 2513
    driverClassName: org.postgresql.Driver
  docker:
    compose:
      enabled: true
      skip:
        in-tests: true
      lifecycle-management: start_and_stop
server:
  port: 8080
bot:
  name: '@AvitoAnalyticsDevelopmentBot'
  token: 7741282007:AAEdXGpLGe7fImfInHTsCnvChHrDnoTkhdo
avito:
  statistic:
    max_items_per_request: 200
  ads:
    max_items_per_request: 100